files:
  customer-blacklist: src/main/resources/customer_blacklist.csv
  voucherRecord: src/main/resources/voucher_record.csv

#---
#spring:
#  profiles:
#    active: release
#
#---
#spring:
#  config:
#    activate:
#      on-profile: dev

