

---
spring:
  config:
    activate:
      on-profile: "dev"

classpath.voucher-storage: classpath:voucher_storage.txt
classpath.customer-blacklist: customer_blacklist.csv

---
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: jdbc:h2:tcp://localhost/~/springboot_basic
    driver-class-name: org.h2.Driver
    username: sa
    password: